services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - miniodata:/data
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_KRAFT_CLUSTER_ID: 3bP06iLFRouGUXD9eazcMg

      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://host.docker.internal:9094
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data

      KAFKA_TOPIC: ${KAFKA_TOPIC}
    volumes:
      - kafka_data:/bitnami/kafka
    command: >
      sh -c "
        /opt/bitnami/scripts/kafka/run.sh & 
        sleep 5 && 
        kafka-topics.sh --create --if-not-exists --topic ${KAFKA_TOPIC} --partitions 1 --replication-factor 1 --bootstrap-server localhost:9092 &&
        tail -f /dev/null
      "
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - minio
    environment:
      APP_PORT: ${APP_PORT:-8080}
    ports:
      - "${APP_PORT:-8080}:8080"
    restart: on-failure

volumes:
  miniodata:
  kafka_data: