services:
  postgres:
    container_name: eventbooker_postgres
    image: postgres:latest
    stop_grace_period: 30s
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/0001_init.up.sql:/docker-entrypoint-initdb.d/0001_init.up.sql
      - ./migrations/0002_add_users_and_auth.up.sql:/docker-entrypoint-initdb.d/0002_add_users_and_auth.up.sql
    ports:
      - "${DATABASE_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_KRAFT_CLUSTER_ID: 3bP06iLFRouGUXD9eazcMg

      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://host.docker.internal:9094
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
    volumes:
      - kafka_data:/bitnami/kafka

  app:
    container_name: eventbooker_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT:-8080}
      DATABASE_HOST: postgres
      KAFKA_URL: kafka:9092
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_HOURS: ${JWT_EXPIRATION_HOURS:-24}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      DEFAULT_PAYMENT_TIMEOUT_MINUTES: ${DEFAULT_PAYMENT_TIMEOUT_MINUTES:-30}
    ports:
      - "${APP_PORT:-8080}:8080"
    restart: on-failure

  frontend:
    container_name: eventbooker_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - app
    restart: on-failure

volumes:
  pgdata:
  kafka_data: